# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trackTypeRows.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13trackTypeRows.proto\x12\x0b\x63\x64sspackage\"\x91\x02\n\rTrackTypeRows\x12+\n\x03tag\x18\x01 \x03(\x0b\x32\x1e.cdsspackage.TrackTypeRows.Tag\x12\x36\n\x05track\x18\x02 \x03(\x0b\x32\'.cdsspackage.TrackTypeRows.TrackTypeRow\x1a!\n\x03Tag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1ax\n\x0cTrackTypeRow\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x03(\x01\x12:\n\x03val\x18\x04 \x03(\x0b\x32-.cdsspackage.TrackTypeRows.TrackTypeRow.Value\x1a\x12\n\x05Value\x12\t\n\x01v\x18\x03 \x03(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trackTypeRows_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACKTYPEROWS._serialized_start=37
  _TRACKTYPEROWS._serialized_end=310
  _TRACKTYPEROWS_TAG._serialized_start=155
  _TRACKTYPEROWS_TAG._serialized_end=188
  _TRACKTYPEROWS_TRACKTYPEROW._serialized_start=190
  _TRACKTYPEROWS_TRACKTYPEROW._serialized_end=310
  _TRACKTYPEROWS_TRACKTYPEROW_VALUE._serialized_start=292
  _TRACKTYPEROWS_TRACKTYPEROW_VALUE._serialized_end=310
# @@protoc_insertion_point(module_scope)
