# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrack.proto\x12\x0b\x63\x64sspackage\"\xa7\x01\n\x05Track\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x12\n\x05srate\x18\x04 \x01(\x01H\x00\x88\x01\x01\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12%\n\x04\x64\x61ta\x18\x06 \x03(\x0b\x32\x17.cdsspackage.Track.Data\x1a\x1f\n\x04\x44\x61ta\x12\n\n\x02ts\x18\x01 \x01(\x01\x12\x0b\n\x03val\x18\x02 \x03(\x02\x42\x08\n\x06_srateb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'track_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACK._serialized_start=29
  _TRACK._serialized_end=196
  _TRACK_DATA._serialized_start=155
  _TRACK_DATA._serialized_end=186
# @@protoc_insertion_point(module_scope)
